name: macos

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: check Xcode
      run: xcode-select -p
    - name: Build the App
      run: cd 'Activity Logger/' && xcodebuild -target 'Activity Logger' -configuration Release
